- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/config.py
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/migrations/migrate_to_4101.py
- src/Products/PloneMeeting/profiles/__init__.py
- src/Products/PloneMeeting/profiles/testing/import_data.py
- src/Products/PloneMeeting/skins/plonemeeting_styles/plonemeeting.css.dtml
- src/Products/PloneMeeting/skins/plonemeeting_templates/meetingconfig_view.pt
- src/Products/PloneMeeting/tests/helpers.py
- src/Products/PloneMeeting/tests/testMeetingConfig.py
- src/Products/PloneMeeting/tests/testWorkflows.py
- src/Products/PloneMeeting/utils.py
Moved MeetingConfig.onMeetingTransitionItemTransitionToTrigger to MeetingConfig.onMeetingTransitionItemActionToExecute, in addition to be able to trigger a transition on every items of a meeting when a transition is triggered on a meeting, it is now possible to execute a TAL expression, see #MPMPHAI-39
> MPMPHAI-39 : MeetingConfig.onMeetingTransitionItemActionToExecute

- CHANGES.rst
- src/Products/PloneMeeting/browser/views.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
I've fixed a bug that happens when redefining 'group_position_type' parameter in view.printAssembly and adapted the tests to test this case.
> Fixed a bug in view.printAssembly

- CHANGES.rst
- src/Products/PloneMeeting/overrides.zcml
This was tested locally and should not cause any problem with instances without collective.solr.
> Fix search with SolR

- CHANGES.rst
- src/Products/PloneMeeting/Meeting.py
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/faceted_conf/default_dashboard_items_widgets.xml
- src/Products/PloneMeeting/faceted_conf/upgrade_step_4104_add_item_widgets.xml
- src/Products/PloneMeeting/migrations/migrate_to_4104.py
- src/Products/PloneMeeting/skins/plonemeeting_styles/plonemeeting.css.dtml
- src/Products/PloneMeeting/tests/testContacts.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
- src/Products/PloneMeeting/vocabularies.py
- src/Products/PloneMeeting/vocabularies.zcml
- Added `Products.PloneMeeting.vocabularies.copygroupsvocabulary` (faceted) and
`Products.PloneMeeting.vocabularies.itemcopygroupsvocabulary` (MeetingItem) vocabularies
- moved `MeetingItem.copyGroup` vocabulary from `listCopyGroups` to `Products.PloneMeeting.vocabularies.itemcopygroupsvocabulary`
- factorized the way advices and copy groups are displayed on item view (`displayAdvisers/displayCopyGroups`)
- adapted tests accordingly
See #PMSER-54
> - Added faceted filter `Copy groups`:

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/tests/testUtils.py
- src/Products/PloneMeeting/utils.py
So it is possible to send an e-mail to arbitrary users. Renamed parameter `permissionOrSuffixOrRoleOrGroupIds` to `value`.
See #MPMSPII-4
> Added parameter `isUserIds` to `utils.sendMailIfRelevant`

- CHANGES.rst
- src/Products/PloneMeeting/content/category.py
- src/Products/PloneMeeting/tests/testMeetingCategory.py
Display also disabled categories in vocabulary so it is visible on category view.
See #PM-3395
> For field `MeetingCategory.category_mapping_when_cloning_to_other_mc`

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/browser/templates/header_item.pt
- src/Products/PloneMeeting/browser/viewlets.py
- src/Products/PloneMeeting/content/meeting.py
- src/Products/PloneMeeting/interfaces.py
- src/Products/PloneMeeting/profiles/__init__.py
- src/Products/PloneMeeting/skins/plonemeeting_templates/meetingconfig_view.pt
- src/Products/PloneMeeting/tests/testMeeting.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
To enable computation of item reference for items decided out of meeting. Now item reference is updated when item inserted/removed from a meeting but also when back to validated and for transitions deciding out of meeting.
See #PM-3099
> Added parameter `MeetingConfig.computeItemReferenceForItemsOutOfMeeting`

- CHANGES.rst
- setup.py
- src/Products/PloneMeeting/__init__.py
- src/Products/PloneMeeting/monkey.py
- src/Products/PloneMeeting/testing.py
- src/Products/PloneMeeting/tests/testMeetingConfig.py
Fixed `monkey.validate` (load `monkey` in tests so it is taken into account).
See #PM-3768
> Rely on `archetypes.schematuning` (thought it was already the case).

- CHANGES.rst
- src/Products/PloneMeeting/profiles/default/registry.xml
> Enable `display_below_content_title_on_views` and `display_photo_label_on_views` in `collective.contact.core` registry parameters.

- CHANGES.rst
- src/Products/PloneMeeting/adapters.py
- src/Products/PloneMeeting/browser/templates/display_annexes.pt
- src/Products/PloneMeeting/browser/templates/meeting_view.pt
- src/Products/PloneMeeting/browser/views.py
- src/Products/PloneMeeting/tests/testAnnexes.py
The confidential annexes were not downloadable but the annex type icon was display and on hover, the `tooltipster` was empty.
See #PM-3890
> Fixed annex type icon wronlgy displayed on meeting view to users not able to access confidential annexes. 

- CHANGES.rst
- src/Products/PloneMeeting/columns.py
- src/Products/PloneMeeting/model/adaptations.py
So it is possible to define an arbitrary new custom title for the transition, before it was taking the transition id, now it is possible to override several different transition title for same transition id in different workflows.
See #PM-3885
> Turned `adaptations.WAITING_ADVICES_FROM_STATES` value `use_custom_transition_title_for` from a tuple of transitions ids to a dict

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/tests/PloneMeetingTestCase.py
- src/Products/PloneMeeting/tests/helpers.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
Moved the `review_states` computation logic from `MeetingItem.listMeetingsAcceptingItems` to `MeetingConfig._getMeetingsAcceptingItemsQuery` so calling `MeetingConfig.getMeetingsAcceptingItems` will always be correct when `review_states=[]`.
This fixes a bug in `imio.pm.ws.soap.soapview.SOAPView._meetingsAcceptingItems` that was returning the same meetings accepting items no matter user was `MeetingManager` or not (was actually always returning meetings accepting items as if user was a `MeetingManager`).
See #MOD-903
> In `MeetingConfig.getMeetingsAcceptingItems`

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/tests/testMeetingConfig.py
So it is possible to remove a delay aware adviser config if it was never used and to change the `for_item_created_from` if it is not an auto asked advice.
See #PM-3910
> Adapted `MeetingConfig.validate_customAdvisers`

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/ToolPloneMeeting.py
- src/Products/PloneMeeting/content/category.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
- src/Products/PloneMeeting/tests/testWFAdaptations.py
- src/Products/PloneMeeting/tests/testWorkflows.py
when cloning an item, this way we avoid problems with category not selectable by `MeetingManager` leading to items not cloned (recurring items, delayed items, ...). Added `MeetingItem.get_successor` helper that will return the last (and very often only) successor.
See #PM-3918
> Make MeetingManager bypass `MeetingCategory.using_groups` check

- CHANGES.rst
- src/Products/PloneMeeting/browser/views_unrestricted.py
- src/Products/PloneMeeting/content/meeting.py
- src/Products/PloneMeeting/safe_utils.py
- src/Products/PloneMeeting/tests/testMeeting.py
- src/Products/PloneMeeting/tests/testUtils.py
- src/Products/PloneMeeting/utils.py
- src/Products/PloneMeeting/workflows/meeting.py
that will manage updating first item number of the meeting.  This way the method is callable from a TAL expression and we may use it when necessary. Moreover, the parameter `get_items_additional_catalog_query={}` will let manage cases where items to take into account are not every items but only a subset of items.
Added `safe_utils.set_dx_value` that will let set a value for a DX content attribute from a `RestrictedPython` call.
See #SUP-24646
> Added `Meeting.update_first_item_number`

- CHANGES.rst
- src/Products/PloneMeeting/migrations/migrate_to_4204.py
- src/Products/PloneMeeting/profiles.zcml
- src/Products/PloneMeeting/profiles/default/metadata.xml
- src/Products/PloneMeeting/setuphandlers.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
- src/Products/PloneMeeting/tests/testSetup.py
Added upgrade step to 4204.
See #PM-3934
> Added `_configurePortalRepository` in `setuphandlers.py` to remove default Plone types that are versionable (`Document`, `Event`, ...)

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/migrations/migrate_to_4204.py
- src/Products/PloneMeeting/profiles/__init__.py
- src/Products/PloneMeeting/profiles/testing/import_data.py
- src/Products/PloneMeeting/skins/plonemeeting_templates/meetingconfig_view.pt
- src/Products/PloneMeeting/tests/testMeetingConfig.py
- src/Products/PloneMeeting/tests/testWorkflows.py
As information is in `MeetingConfig.itemWFValidationLevels`, method `MeetingConfig.getTransitionsForPresentingAnItem` is kept and does the job.
See #PM-3939
> Removed field `MeetingConfig.transitionsForPresentingAnItem`

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/interfaces.py
`MeetingConfig._createOrUpdateAllPloneGroups` parameter `only_group_ids=False` was renamed to `dry_run_return_group_ids=False`.
See #PM-3530
> Added adaptable method `MeetingConfig._custom_createOrUpdateGroups` to ease a profile adding a custom `MeetingConfig` related group.

- CHANGES.rst
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/events.zcml
- src/Products/PloneMeeting/tests/testMeetingCategory.py
> Make sure a `MeetingCategory` can not be renamed if it is used.

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/content/meeting.py
- src/Products/PloneMeeting/tests/testVotes.py
Fixed `Meeting._get_contacts` to take into account parameter `uids` order when given. Fixed `MeetingItem.get_item_votes`, use an `OrderedDict` instead a `Dict` to store voters to preserve order.
See #SUP-25712
> Fixed `ItemDocumentGenerationHelperView.print_votes`, make sure voters are ordered when `include_voters=True`.

- CHANGES.rst
- src/Products/PloneMeeting/MeetingConfig.py
- src/Products/PloneMeeting/tests/testWFAdaptations.py
Removing a `waiting_advices` complementary configuration is allowed, only check for items in review_state `waiting_advices` if the `waiting_advices` WFA was removed.
See #PM-4077
> Fixed `MeetingConfig.validate_workflowAdaptations`

- CHANGES.rst
- src/Products/PloneMeeting/browser/views.py
> Adapted `BatchActions` to use new attribute `available_permission` to avoid overriding the `available` method.

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/config.py
- src/Products/PloneMeeting/content/meeting.py
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/tests/testContacts.py
This rely now on `config.MEETING_ATTENDEES_ATTRS` that makes sure that every meeting attendees custom attributes are cleaned when item is removed. See #PM-4116
> When removing an item from a meeting, make sure item `UID` is removed from `Meeting.item_attendees_positions` and `Meeting.item_attendees_order`.

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/browser/advices.py
- src/Products/PloneMeeting/browser/templates/advices-icons-infos.pt
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/skins/plonemeeting_styles/plonemeeting.css.dtml
- src/Products/PloneMeeting/tests/testFaceted.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
- src/Products/PloneMeeting/vocabularies.py
> Fixed `ItemOptionalAdvicesVocabulary` to manage correctly missing terms when it involves userids

- CHANGES.rst
- src/Products/PloneMeeting/browser/overrides.py
- src/Products/PloneMeeting/config.py
- src/Products/PloneMeeting/events.py
- src/Products/PloneMeeting/migrations/migrate_to_4210.py
- src/Products/PloneMeeting/profiles.zcml
- src/Products/PloneMeeting/profiles/default/metadata.xml
- src/Products/PloneMeeting/tests/PloneMeetingTestCase.py
> Removed `config.BARCODE_INSERTED_ATTR_ID`, we do not use it anymore to check if a barcode was inserted, we rely on the `scan_id`.

- CHANGES.rst
- src/Products/PloneMeeting/MeetingItem.py
- src/Products/PloneMeeting/tests/testMeetingItem.py
> When cloning an item, re-apply auto committees in case configuration changed
