src/Products/PloneMeeting/browser/views.py

added functions to extract attendance statistics from contacts data on meetings

attendance statistics

---

CHANGES.rst
src/Products/PloneMeeting/config.py
src/Products/PloneMeeting/tests/testMeetingItem.py

Mister G, can you reviewing my code please ....
thank's a lot

Ticket pm 939

---

CHANGES.rst
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/events.py

Sup 8615 adapt mail notifications

---

CHANGES.rst
src/Products/PloneMeeting/config.py
src/Products/PloneMeeting/tests/testMeetingItem.py

Ticket8973 keep out decided on templates

---

CHANGES.rst
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/config.py
src/Products/PloneMeeting/tests/testAdvices.py

Gauthier, it's for you :1st_place_medal:

add new field : decisionSuite

---

CHANGES.rst
src/Products/PloneMeeting/Meeting.py
src/Products/PloneMeeting/MeetingConfig.py
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/ToolPloneMeeting.py
src/Products/PloneMeeting/browser/adviceinheritance.py
src/Products/PloneMeeting/browser/configure.zcml
src/Products/PloneMeeting/browser/itemassembly.py
src/Products/PloneMeeting/browser/itemattendee.py
src/Products/PloneMeeting/browser/itemchangeorder.py
src/Products/PloneMeeting/browser/itemsignatures.py
src/Products/PloneMeeting/browser/itemvotes.py
src/Products/PloneMeeting/browser/overrides.py
src/Products/PloneMeeting/browser/views.py
src/Products/PloneMeeting/events.py
src/Products/PloneMeeting/ftw_labels/configure.zcml
src/Products/PloneMeeting/interfaces.py
src/Products/PloneMeeting/migrations/migrate_to_4200.py
src/Products/PloneMeeting/overrides.zcml
src/Products/PloneMeeting/utils.py

En attente de merge collective.eeafaceted.z3ctable et collective.eeafaceted.batchactions

Mod 727 enable ftw labels batch action

---

src/Products/PloneMeeting/browser/meeting.py
src/Products/PloneMeeting/config.py
src/Products/PloneMeeting/content/held_position.py
src/Products/PloneMeeting/content/meeting.py
src/Products/PloneMeeting/tests/testMeeting.py
src/Products/PloneMeeting/vocabularies.py

Completed MeetingView.warn_assembly as there may be cases where only one signature is used

---

CHANGES.rst
src/Products/PloneMeeting/browser/itemvotes.py
src/Products/PloneMeeting/tests/testVotes.py

Completed `IEncodeSecretVotes.validate_votes` to ensure values are integers.

---

CHANGES.rst
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/tests/testToolPloneMeeting.py
src/Products/PloneMeeting/utils.py

Fixed `MeetingItem.modified` not updated when item cloned.

---

CHANGES.rst
src/Products/PloneMeeting/migrations/migrate_to_4201.py
src/Products/PloneMeeting/model/adaptations.py
src/Products/PloneMeeting/profiles.zcml
src/Products/PloneMeeting/profiles/default/metadata.xml
src/Products/PloneMeeting/tests/testWFAdaptations.py

proposingGroup member was not able to add annexes. Added upgrade step to `4201` to fix item WF and update existing items WF role mappings.
See #SUP-22586

Fixed WFAdaptation `returned_to_proposing_group`

---

CHANGES.rst
src/Products/PloneMeeting/content/meeting.py

Added new field `Meeting.mid_start_date`.

---

CHANGES.rst
src/Products/PloneMeeting/MeetingItem.py

Begin adaptations to be able to return linked items in pm.restapi

---

CHANGES.rst
src/Products/PloneMeeting/migrations/migrate_to_4204.py
src/Products/PloneMeeting/profiles.zcml
src/Products/PloneMeeting/profiles/default/types/MeetingItemRecurring.xml
src/Products/PloneMeeting/profiles/default/types/MeetingItemTemplate.xml
src/Products/PloneMeeting/skins/plonemeeting_plone/displayContentsTab.py
src/Products/PloneMeeting/tests/testMeetingItem.py

Added possibility to add images to `MeetingItemTemplate/MeetingItemReccuring`. Display the `folder_contents` tab on items of the `MeetingConfig`.

---

CHANGES.rst
src/Products/PloneMeeting/browser/templates/generationlinks.pt
src/Products/PloneMeeting/etags.py
src/Products/PloneMeeting/skins/plonemeeting_styles/plonemeeting.css.dtml
src/Products/PloneMeeting/tests/testViews.py

Make sure dashboard cache is invlaidated (etags) when a meeting date changed, this is necessary so meeting date faceted filters are correct.

---

CHANGES.rst
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/tests/testAdvices.py
src/Products/PloneMeeting/tests/testMeetingItem.py

Fixed item advices invalidation, advices were removed but not unindexed.

---

CHANGES.rst
src/Products/PloneMeeting/ToolPloneMeeting.py
src/Products/PloneMeeting/tests/testMeetingItem.py
src/Products/PloneMeeting/vocabularies.py

Pm 3861 clone item annex only pdf config changed correct branch

---

CHANGES.rst
src/Products/PloneMeeting/ToolPloneMeeting.py
src/Products/PloneMeeting/monkey.py
src/Products/PloneMeeting/tests/PloneMeetingTestCase.py

Moved `monkey._listAllowedRolesAndUsers` to `imio.helpers.patches._listAllowedRolesAndUsers`.

---

CHANGES.rst
src/Products/PloneMeeting/ToolPloneMeeting.py
src/Products/PloneMeeting/migrations/migrate_to_4200.py
src/Products/PloneMeeting/migrations/migrate_to_4208.py
src/Products/PloneMeeting/migrations/migrate_to_4209.py
src/Products/PloneMeeting/profiles.zcml
src/Products/PloneMeeting/profiles/default/metadata.xml
src/Products/PloneMeeting/tests/PloneMeetingTestCase.py
src/Products/PloneMeeting/tests/testAnnexes.py
src/Products/PloneMeeting/tests/testMeetingItem.py
src/Products/PloneMeeting/tests/testToolPloneMeeting.py

Base implementation for keeping annex with scan_id when sent to another MC and an annex_type correspondence is defined

---

CHANGES.rst
src/Products/PloneMeeting/browser/views.py
src/Products/PloneMeeting/tests/testVotes.py

(`does_not_……vote`, `not_found`, `invalid`, `blank`). Adapted parameter `single_vote_value` so we can define a single value or a different value for each `vote_values`.

Completed `print_votes` so it manages every `vote_values`

---

CHANGES.rst
src/Products/PloneMeeting/MeetingConfig.py
src/Products/PloneMeeting/MeetingItem.py
src/Products/PloneMeeting/tests/testMeetingConfig.py
src/Products/PloneMeeting/tests/testWFAdaptations.py
src/Products/PloneMeeting/vocabularies.py

WFA hide_decisions_when_under_writing per powerobservers
